version: '3'
services:
  nats-server:
    image: nats:latest
  
  
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/microservice-productos-test/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    depends_on:
      - nats-server
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}
  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/microservice-productos-test/image-registry/products-ms
    environment:
      - PORT=3001
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=${NATS_SERVERS}

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDER_DATABASE_URL=${ORDER_DATABASE_URL}
    image: southamerica-east1-docker.pkg.dev/microservice-productos-test/image-registry/orders-ms
    #restart: always
    environment:
      - PORT=3002
      - DATABASE_URL=${ORDER_DATABASE_URL}
      - NATS_SERVERS=${NATS_SERVERS}

  # orders-db:
  #   container_name: orders_database
  #   image: postgres:16.2
  #   restart: always
  #   volumes:
  #     - ./orders-ms/postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=123456
  #     - POSTGRES_DB=ordersdb
  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/microservice-productos-test/image-registry/payments-ms
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIP_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIP_CANCEL_URL=${STRIPE_CANCEL_URL}
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
  
  ngrok:
    depends_on:
      - payments-ms
    image: ngrok/ngrok:latest
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: ["http", "payments-ms:3003"]
    ports:
      - 4040:4040
  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/microservice-productos-test/image-registry/auth-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}