apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payment
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payment
    spec:
      containers:
      - image: southamerica-east1-docker.pkg.dev/microservice-productos-test/image-registry/payments-ms
        name: payments-ms
        env:
          - name: PORT
            value: "3003"
          - name: NATS_SERVERS
            value: "nats://nats:4222"
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: payments-ms-secrets
                key: stripe_secret_key
          - name: STRIPE_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: payments-ms-secrets
                key: stripe_webhook_secret
          - name: STRIP_SUCCESS_URL
            value: "http://localhost:3003/payments/success"
          - name: STRIP_CANCEL_URL
            value: "http://localhost:3003/payments/cancel"
        resources: {}
status: {}
