apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orders
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orders
    spec:
      containers:
      - image: southamerica-east1-docker.pkg.dev/microservice-productos-test/image-registry/orders-ms
        name: orders-ms
        env:
          - name: PORT
            value: "3000"
          - name: NATS_SERVERS
            value: "nats://nats:4222"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: orders-secretes
                key: database_url
        resources: {}
status: {}
