apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth
    spec:
      containers:
      - image: southamerica-east1-docker.pkg.dev/microservice-productos-test/image-registry/auth-ms
        name: auth-ms
        env:
          - name: PORT
            value: "3000"
          - name: NATS_SERVERS
            value: "nats://nats:4222"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: auth-ms-secrets
                key: database_url
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-ms-secrets
                key: jwt_secret
        resources: {}
status: {}
